### ISSUE TITLE
Passing arguments to docker build

### ISSUE THREAD

**Issue by SquidDev** [ocurrent/ocurrent#101]
I've been using ocurrent for a little over a month now, and found it incredibly useful and helpful (thank you all!).

One thing I'd quite like to do, but been unable to figure out, is pass additional arguments to `docker build`. More specifically, I'd like to impose a CPU and memory limit on builds (via the `--cpus` and `-m` flags).

I'd be happy to put together a PR which adds a `?build_args` argument to `S.DOCKER.build` (similar to `run`'s `run_args`), I just wanted to get people's opinions on this, and check there wasn't an existing approach I was missing?

**Comment by talex5** [comment]
Sounds good to me!

BTW, I'd be interested to hear what you're using OCurrent it for too, if you can share that.

**Comment by CraigFe** [comment]
https://github.com/ocurrent/ocurrent/pull/102 is now merged, thanks!

FWIW, I'm also very interested in knowing what you're using OCurrent for :blush:

**Comment by SquidDev** [comment]
Sorry, should have added a "Closes #101" within the PR.

I'm afraid I'm not doing anything especially serious with it. I'm just running [a small personal CI server](https://vampyroteuthis.squiddev.cc/) for some of my projects which don't fit within GH Actions, either because they have massive dependency caches or demand more complex build steps (multi-repo builds for instance).
