### ISSUE TITLE
pr comments + per branch subdomain names

### ISSUE THREAD

**Issue by kanishka-work** [ocurrent/ocurrent#254]
It would be nice if occurent can eventually match this Vercel/netlify feature:

![image](https://user-images.githubusercontent.com/1385802/114249755-7a747380-9969-11eb-862a-dec5948081d1.jpg)

**Comment by dra27** [comment]
Indeed - this is wanted for opam-repo-ci (to replace Camelus notifications) and odoc, to allow documentation previews. Some initial experimenting was done a while ago in #74.

**Comment by dra27** [comment]
Closing (if you don't mind), as we don't need an issue in ocurrent to track the need
