### ISSUE TITLE
Documentation: Github App Webhook URL

### ISSUE THREAD

**Issue by d4hines** [ocurrent/ocurrent#260]
Hello,
Thanks for this tool - it's going to be really helpful for our Tezos benchmarking project, and the github app interface is really sweet.

That said, the documentation around the Github App usage is lacking. There are many details left as an exercise to the user, and I feel quite exercised in that respect. I'm currently hung up on what URL to paste into the configuration of my Github App. That information is obviously encoded in the [example]( https://github.com/ocurrent/ocurrent/blob/master/examples/github_app.ml#L58); however, this is my first ocurrent project, and I'm unfamiliar with the syntax. I cannot find the documentation for routes any where [on the API docs site]( https://ocurrent.github.io/ocurrent/current_web/index.html). Thus the meaning of `... /? nil` is mysterious to me. I'm sure if I were an Emacs user Merlin could find the docstrings for me, but on VS Code nothings coming up via ocamllsp, at least not in the current-bench project.

Any of the following would be a big help to future users (ranked by preference)
- A detailed walkthrough that makes no assumptions of familiarity with Github Apps or Ocurrent
- Detailed annotations in the example
- Documentation somewhere on the docs site.

**Comment by gs0510** [comment]
@d4hines The Github webhook you require for the app should be something along the lines of `http://<host+port where your ocurrent pipeline is running>/webhooks/github`.

I agree that more documentation is required for users unfamiliar with ocurrent and github apps. :)

**Comment by talex5** [comment]
>  I cannot find the documentation for routes any where on the API docs site.

Routes is a separate library, documented at https://github.com/anuragsoni/routes.

(once https://github.com/ocaml/odoc is ready, we'll be able to provide unified docs in one place)

**Comment by dra27** [comment]
I believe that the current_bench documentation/process for this changed/improved (@gs0510?) which hopefully mitigates the precise issue here (getting current_bench up and running) for the future. For the examples in ocurrent itself, it's a little bit awkward to document GitHub Apps as well as how to use them (the example is attempting to go from the perspective of someone who knows about GitHub Apps and wants to see how you do them in ocurrent).

For linking the documentation properly, there is light at the end of the tunnel! The new unified docs system is previewable at v3.ocaml.org. Over the coming months, it should be possible to switch "private" docs sets to include dependencies in the same way, but for now if you start at the documentation for `Current_web.Site.v` at https://v3.ocaml.org/p/current_web/0.5/doc/Current_web/Site/index.html#val-v then you can see links straight into the Routes library, for example into [`Routes.s`](https://v3.ocaml.org/p/routes/0.8.0/doc/Routes/index.html#val-s).

PRs extending the examples further are of course always welcome, but I'm going to close this one for now as it's not entirely clear what we'd add. Please do feel free to re-open as necessary!
