### ISSUE TITLE
web-ui: Make the cancel button available in the logs

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/ocurrent#286]
This is useful to have a quick access to this for jobs that are stalling, or that will overload the cluster.
On opam-repo-ci there is too much going on on the admin UI for it to be usable/enjoyable.

**Comment by novemberkilo** [comment]
Clarification -- want the ability to cancel all running jobs that are associated to a single commit.  See screenshot for an example.

![Firefox_Screenshot_2022-05-04T01-01-19 268Z](https://user-images.githubusercontent.com/181086/166610389-8cd8a295-41bf-4fe9-9306-716ff38f8338.png)
