### ISSUE TITLE
Wrong name used for repository

### ISSUE THREAD

**Issue by patricoferris** [ocurrent/ocurrent#289]
Had this repo pinned to upstream rather than the current release and I think there's a bug in the name of the repository used when getting the default ref:

https://github.com/ocurrent/ocurrent/blob/7ea8c2164e2af896e7060e53ea53110e66ab147d/plugins/github/api.ml#L318-L331

The `repo` parameter is passed `name` but that is now the name of the default branch and not the name of the repository itself. Noticed this because when trying to fetch something it was fetching `https://github.com/patricoferris/main.git`

**Comment by tmcgilchrist** [comment]
@patricoferris How are you triggering this failure? I have some ideas on where this is going wrong.

**Comment by patricoferris** [comment]
I was using it in a project, but the `docs/examples/github.ml` hits the same problem:

```
dune exec -- doc/examples/github.exe ocurrent/ocurrent --github-token-file /path/to/token
...
"state":"failure","description":"Command \"git\" \"clone\" \"--recursive\" \"-q\" \"https://github.com/ocurrent/master.git\"
```

I think I have it fixed in a branch but it's mixed up with other things I was doing there so not easy to PR, but something like: 

```ocaml
let get_default_ref t { Repo_id.owner; name = repo_name } =
    let variables = [
      "owner", `String owner;
      "name", `String repo_name;
    ] in
    exec_graphql t ~variables query_default >|= fun json ->
    try
      let open Yojson.Safe.Util in
      let data = json / "data" in
      handle_rate_limit t "default_ref" (data / "rateLimit");
      let repo = data / "repository" in
      let def = repo / "defaultBranchRef" in
      let prefix = def / "prefix" |> to_string in
      let name = def / "name" |> to_string in
      let hash = def / "target" / "oid" |> to_string in
      let committed_date = def / "target" / "committedDate" |> to_string in
      { Commit_id.owner; repo = repo_name ; id = `Ref (prefix ^ name); hash; committed_date }
```
