### ISSUE TITLE
Show line numbers misses certain line numbers when streaming logs

### ISSUE THREAD

**Issue by shakthimaan** [ocurrent/ocurrent#313]
When testing with https://github.com/ocurrent/ocaml-ci/pull/429, the `Show line numbers and allow jumping to specific lines in jobs logs` https://github.com/ocurrent/ocurrent/pull/309 does loose the line numbers at certain points when streaming the logs.

**Comment by punchagan** [comment]
Thanks for testing it out, @shakthimaan ! Could you elaborate in the issue what you mean by certain points or share a screencast? There's a "debounce" of 200ms before trying to update line numbers on the newly streamed lines to avoid doing too much work on the page as lots of data comes streaming in. Could the behavior you see be explained by that?

**Comment by punchagan** [comment]
@tmcgilchrist could you describe what you see in a little more detail to help identify the problem? Thanks!

**Comment by tmcgilchrist** [comment]
I was seeing the 200ms `debounce` and the associated shifting alignment of the page contents. It's working as expected.
