### ISSUE TITLE
hub.docker.com images and tags

### ISSUE THREAD

**Issue by hannesm** [ocurrent/ocurrent#375]
Hello,

sorry if this is the wrong repository to report such a question, I simply do not know where the right one would be (and https://hub.docker.com/r/ocaml/opam/ doesn't mention any).

On https://hub.docker.com/r/ocaml/opam/ it states: "There are also some alternate OCaml configurations such as [with flambda enabled](https://opam.ocaml.org/packages/ocaml-option-flambda/) or [with frame pointers enabled](https://opam.ocaml.org/packages/ocaml-option-fp/)." -- but I do not understand which images have flambda enabled (or frame pointers, or no flat float array). I'm using the fedora-35 4.14 line.

So, my question is: are fedora 35 flambda containers available somewhere? Would it be possible to add such?

Thanks for all your hard work.

**Comment by mtelvers** [comment]
Hi @hannesm, these images would have `flambda` or `fp` in the tag.  For example,

    docker pull ocaml/opam:debian-11-ocaml-4.14
    docker pull ocaml/opam:debian-11-ocaml-4.14-fp
    docker pull ocaml/opam:debian-11-ocaml-4.14-flambda
    docker pull ocaml/opam:debian-11-ocaml-4.14-flambda-fp

These are not built for Fedora, but they are for Debian and Alpine.

**Comment by avsm** [comment]
Hannes, how important is it for you to use Fedora with these variants? We can promote an RPM distro to Tier1, but there's a significant ongoing cost in terms of the number of images and variants pushed.  And RPM distros tend to be less reliable in CI (specifically, due to dnf).  But if you really need Fedora, we can add Fedora...

**Comment by hannesm** [comment]
Thanks for your answers. I was asking since the qubes-mirage-firewall is built on fedora-35 (see https://github.com/mirage/qubes-mirage-firewall and the contained Dockerfile) -- the main reason AFAIU is that QubesOS is based on Fedora, and to ease building it on QubesOS, that Fedora is used. Now, I was curious whether we can use flambda there, but couldn't find any pre-built docker images.

I have not much clue about the different Linux distributions, and thus am not keen to switch over to "debian" or "alpine" for producing the release of qubes-mirage-firewall. In the time being I'm fine to not use flambda.

**Comment by hannesm** [comment]
More than a year later, I'm closing this. It doesn't specifically look like anyone intends to work on improving the current status, neither on documenting the reasoning behind what images are available.

Have a nice day.
