### ISSUE TITLE
Update `Current_github` to support specific handler

### ISSUE THREAD

**Issue by maiste** [ocurrent/ocurrent#376]
In the current state of the `webhook` function, the user cannot influence the way `Current_github` has to deal with the events it receives from *GitHub*. We should provide a way to give an `event handler` to make it possible to decide how to handle them from a user perspective.

**Comment by tmcgilchrist** [comment]
The web hook handler is tightly coupled with the Github plugin machinery. Users providing their own function could break the ocurrent machinery. What use case are you trying to support?

**Comment by maiste** [comment]
The case I wanted to cover here was the one where you want to execute different actions when receiving a pull request for example.
That's why I wanted to introduce a new function and not update the old one. It lets the user having a default version.

**Comment by maiste** [comment]
Considering we have found other ways to tackle the problem, I'm closing this issue.
