### ISSUE TITLE
Automatic refresh is annoying on large graphs

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/ocurrent#398]
When looking at the job graph, i have the following use-case:
1) lookup some error log on the userside website
2) open the corresponding subgraph (takes 30s already)
3) lookup some corresponding docker peek logs to rebuild (takes 20s)
4) lookup some more logs on the userside website
5) the page reloads and i have to wait 30s again...
6) leave it to reload, go back to it and it in a reload cycle once again

I don't personally need the automatic refresh feature added in https://github.com/ocurrent/ocurrent/pull/277 at all.
Is there a way to disable it?

**Comment by MisterDA** [comment]
Is the problem that the graph takes too long to load, and you'd like to disable the refresh because you don't have the time to browse the graph between two refreshes, or that the refresh brings you somewhere else?
Another way of solving the problem could be to try to make the graph generation faster.

**Comment by kit-ty-kate** [comment]
that's the former yes. I don't think you can make the graph generation faster and I'd much rather disable it on opam-repo-ci all together as I don't think it's useful there

**Comment by MisterDA** [comment]
The refresh timeout is set here: https://github.com/ocurrent/ocurrent/blob/21dcb15b2b0328a3128168f2d7da23cba238b464/lib_web/main.ml#L40.
I'm not sure how to disable it, maybe with a global config option? Where would it be introduced? If there's no support anymore for the feature, it can also be reverted.
